type: module
private: true
scripts:
  prebuild:codegen: pnpm run --recursive --if-present --aggregate-output prebuild
  prebuild:tsconfig: package-tools monorepo-tsconfig --force
  prebuild: pnpm run '/^prebuild:/'
  prewatch: pnpm run '/^prebuild:/'
  postinstall: >-
    package-tools monorepo-link-binaries --recursive --transparent
    @core/custom-rig
  build: tsc -b ./tsconfig.everything.json
  watch: tsc -b ./tsconfig.everything.json -w
  start: node scripts/start.devel.js
  start:production: node scripts/start.js
  clean: pnpm run --if-present --recursive clean
devDependencies:
  '@biomejs/biome': ^2.4.10
  '@build-script/package-tools': ^0.0.29
  '@core/bootstrap': workspace:^
  '@mpis/monorepo': ^0.0.26
  '@types/debug': ^4.1.13
  dotenv: ^17.4.0
  execa: ^9.6.1
  typescript: ^6.0.2
