packages:
  - .
  - '@adapter/*'
  - '@core/*'
  - '@program/*'
  - '@shared/*'

enablePrePostScripts: true
hoistWorkspacePackages: false

ignoredOptionalDependencies:
  - fsevents
onlyBuiltDependencies:
  - '@biomejs/biome'

strictPeerDependencies: true

hoist: false
publicHoistPattern:
  - "@types/*"
  - "@biomejs/biome"
  - "source-map-support"
  - "@build-script/baseline-rig"
hoistPattern:
  - ""

saveWorkspaceProtocol: rolling
savePrefix: '^'
ignoreWorkspaceCycles: true
nodeOptions: ''

fetchRetries: 1000
networkConcurrency: 3
gitChecks: false
registry: https://registry.npmmirror.com

overrides:
  "@idlebox/logger": "/data/DevelopmentRoot/github.com/gongt/baobao/@idlebox/logger"
#   "@idlebox/node": "/data/DevelopmentRoot/github.com/gongt/baobao/@idlebox/node"
  "@idlebox/common": "/data/DevelopmentRoot/github.com/gongt/baobao/@idlebox/common"
