packages:
  - .
  - '@adapter/*'
  - '@core/*'
  - '@program/*'
  - '@shared/*'

enablePrePostScripts: true

fetchRetries: 1000
gitChecks: false

hoist: false
hoistPattern:
  - ""
hoistWorkspacePackages: false
ignoreWorkspaceCycles: true

ignoredOptionalDependencies:
  - fsevents
networkConcurrency: 3
nodeOptions: ''
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - bufferutil
  - esbuild

publicHoistPattern:
  - "@types/*"
  - "@biomejs/biome"
  - "source-map-support"
  - "@build-script/baseline-rig"
registry: https://registry.npmmirror.com
savePrefix: '^'

saveWorkspaceProtocol: rolling

strictPeerDependencies: true

overrides:
  #   "@idlebox/logger": "/data/DevelopmentRoot/github.com/gongt/baobao/@idlebox/logger"
  "@idlebox/common": "/data/DevelopmentRoot/github.com/gongt/baobao/@idlebox/common"
  "@idlebox/node": "/data/DevelopmentRoot/github.com/gongt/baobao/@idlebox/node"
